### ISSUE TITLE
Expose License Details through Pulse?

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServicePulse#383] opened 2016-10-26 08:01 UTC
ServiceControl 1.24 now exposes license infomation via the REST API

Previously the only info exposed over the REST API was whether the license had expired or not,
Now you can get whether the current license is a trial or not and expiry dates etc. Take a look at -> https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Licensing/LicenseModule.cs for more details 

@Particular/servicepulse-maintainers we did this on the assumption that you might want the option to have a more detailed license error that currently exists

**Comment by WojcikMike** [comment] 2018-04-12 11:14
This is a duplicate of #436 as such I will close this issue.

**Closed by WojcikMike** 2018-04-12 11:14 UTC
Labels: Type: Discussion
