### ISSUE TITLE
Failed messages not being grouped

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServicePulse#210] opened 2015-11-05 13:00 UTC
We have noticed some failed messages are not being grouped and therefore do not appear in ServicePulse Group view

When you look at this screen shot, you can see that the message appears in ServiceInsight, but it is not in the Group view in ServicePulse.

![screendump](https://cloud.githubusercontent.com/assets/8087733/10968951/5250e1aa-83c5-11e5-948f-6ee77299b818.png)

**Comment by petersgiles** [comment] 2015-11-05 22:55
When you navigate to the Failed Messages page have you clicked on the `View All Failed Messages` button? 

When you look through those messages are you able to find the message you are referring to?

The group names are our best approximation of a name for a group of similar messages. Even though they look like the actual Exception text we have made changes to it so they can be subtly different across the whole group.

If you can't find you message in the data presented we might need to get a copy of your Raven Database to better understand your scenario.

**Comment by johnsimons** [comment] 2015-11-06 00:16
We using raven indexes to do the grouping, could those be taking some time to catch up ?

**Comment by petersgiles** [comment] 2015-11-13 01:32
@cjoergensen We haven't heard from you in a while. Was the advice we gave useful? Are you still having this issue?

**Comment by cjoergensen** [comment] 2015-11-13 08:07
@petersgiles we have about 2.500 failed message, so having to go through all of the messages, loading 50 messages pr. page, is not really an option :-)

However we are doing some cleanup and getting rid of a lot of these messages. When we are done with that I will get back to you.

**Comment by petersgiles** [comment] 2015-11-15 23:09
@cjoergensen thanks

**Comment by johnsimons** [comment] 2015-11-16 00:25
@cjoergensen just wondering, are all error messages now grouped ?

**Comment by petersgiles** [comment] 2015-11-30 00:24
@cjoergensen We haven't heard from you in a while. Is there anything else we can do for you?

**Comment by cjoergensen** [comment] 2015-11-30 07:26
@petersgiles Sorry for the delay, we have been insanely busy the last weeks.

We just noticed that we have similar behavoir in our development enviroment. 

Failed Messages appears in ServiceInsight and are can accessed throught the ServiceControl API, http://...:33333/api/errors/, but are not present in ServicePulse.

So i looks like the problem is not related to the grouping, but a more general issue with errors in ServicePulse

Would you like me to send you a copy of our Audit database?

**Comment by petersgiles** [comment] 2015-11-30 08:59
Yes, zip it up and send it to me peter.giles@particular.net . If it isn't too big for email it should get through just fine. If that doesn't work we can make some other arrangement.

**Comment by johnsimons** [comment] 2015-11-30 23:38
Send it via https://www.wetransfer.com/

**Comment by petersgiles** [comment] 2015-12-01 00:31
@cjoergensen 

If you haven't already upgrade to the latest version of our tools.

It looks like you may be suffering from a [bug](https://github.com/Particular/ServiceControl/issues/566) that was fixed in [ServiceControl 1.7.0](https://github.com/Particular/ServiceControl/releases/tag/1.7.0).

It is really important that you read through [these instructions](https://github.com/Particular/ServiceControl/blob/master/tools/ResetConcurrencyFlag/README.md) to fix the messages that are stalled 

I think these are the messages ids that are stuck please ensure that they are in the ServiceControl Error queue
- da7061f0-2aea-7c57-d26d-24b82e75627b 
- 9b0d662a-aaff-6089-0244-9c3ef082641b

If they are you will need to issue these commands on a command line

``` cmd
ResetMessageRetry.exe da7061f0-2aea-7c57-d26d-24b82e75627b
ResetMessageRetry.exe 9b0d662a-aaff-6089-0244-9c3ef082641b
```
After you run this command each message should appear in ServicePulse.

Please tell us if this solves the problem.

Pete

**Comment by cjoergensen** [comment] 2015-12-01 13:01
@petersgiles 

I just checked and none of the messages are in the ServiceControl.Errors Queue.

**Comment by petersgiles** [comment] 2015-12-01 22:47
Looking at your data I can see that there are no failed messages with a status of 1 (unprocessed) 

Messages that are unprocessed appear in ServicePulse

There are two with a status of 3 (Retry Requested)

-    da7061f0-2aea-7c57-d26d-24b82e75627b
-    9b0d662a-aaff-6089-0244-9c3ef082641b

This could be because someone had just issued a retry at the time you backed up the data for me or because they're stuck.

The remainder have either been processed successfully or archived.

Can you give me the message Id of a message that you see in ServiceInsight that you don't see in ServicePulse...You might have to send through another database backup.

**Comment by cjoergensen** [comment] 2015-12-02 07:05
@petersgiles 

I have sent your a new database backup.

The MessageIds in ServiceInsight are:
- 5a8139af-13d0-49ba-a5f9-a5520100893b
- de57a130-fe84-459f-a2fc-a55201007b7d

**Comment by petersgiles** [comment] 2015-12-06 23:29
@cjoergensen I've gone through the data

Those two messages are the same messages I identified before as being in a 'Stuck' State. (there are several identifiers for messages depending on where they are in a conversation) 

-  5a8139af-13d0-49ba-a5f9-a5520100893b => da7061f0-2aea-7c57-d26d-24b82e75627b
-  de57a130-fe84-459f-a2fc-a55201007b7d => 9b0d662a-aaff-6089-0244-9c3ef082641b 

Check your ServiceControl error queue for the 2 Ids you gave me. Then follow the instructions in the previous links. Everything should become unstuck and you will see the messages in ServicePulse again

**Comment by cjoergensen** [comment] 2015-12-07 09:55
@petersgiles 

The Error queue contains none of those messages:
![screen](https://cloud.githubusercontent.com/assets/8087733/11623990/e67999a2-9cd0-11e5-8701-7371fbf79459.png)

**Comment by petersgiles** [comment] 2015-12-07 21:25
@cjoergensen have you looked in the bodies of those 2 errors to see if any of the key material we've identified is in there. Or that the messages are the same in some way. It seems to be worth following up on, you have 2 stuck messages and 2 items in the error queue.

**Comment by cjoergensen** [comment] 2015-12-07 21:33
@petersgiles 
The two messages in the error queue are 'ServiceControl.EndpointControl.InternalMessages.RegisterEndpoint' message. So I don't believe they are related to the messages that we have identified.

**Comment by petersgiles** [comment] 2015-12-07 22:04
@cjoergensen 

This is perplexing. I'll have to ask around for help on this one. Hopefully it won't take too long.

**Comment by mikeminutillo** [comment] 2015-12-08 03:28
@cjoergensen @petersgiles I've had a look at the database provided and the EventLog definitely records these as failed, then retried the next morning, and then no further activity. There are a few cases why this might happen.

1) The processing endpoint failed to process the message and did not forward it to the error queue that is being monitored by SC
2) The processing endpoint succeeded processing the message and did not forward it to the audit queue that is being monitored by SC
3) The processing endpoint has been renamed, moved or decommissioned between when the error happened and when it was retried (i.e. it's still in an input queue waiting to be read)

1 and 2 could be caused by configuration. Either Audit or Error logging may not be switched on or may be sending messages to the wrong queues. 3 is unlikely given the short timing but is worth checking anyway.

If you have an SC log file for the dates of those messages (16th and 17th of Nov) that could help to see if the message was sent. Logs for the other two participating endpoints for those dates and times could also help to diagnose what's happened.

**Comment by cjoergensen** [comment] 2015-12-18 10:13
@petersgiles @mikeminutillo 

Hi guys,

I've done some poking around and I do belive that the effected endpoints has been running with a faulty configuration for a periode of time, which has caused this issue.

Thanks for your assistence!

**Closed** 2016-01-04 21:03 UTC
Labels: Type: Question
