### ISSUE TITLE
Custom checks shows as failed on dashboard even the check is ok

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServicePulse#214] opened 2015-11-10 13:37 UTC
Note the eventlog item that the check is ok

<img width="1577" alt="sp-dashboard" src="https://cloud.githubusercontent.com/assets/125028/11063652/738f300a-87b8-11e5-8fe3-700995afd1ab.PNG">

and looking at the custom checks page its listed as ok as well

<img width="742" alt="sp-custom checls" src="https://cloud.githubusercontent.com/assets/125028/11063662/7eaa5794-87b8-11e5-8fa2-a7e8d5e76eb9.PNG">

### Versions

SC 1.7.4
SP 1.3.4

**Comment by mauroservienti** [comment] 2015-11-10 15:22
The issue is broader, it affects in the same way also the `Endpoints` indicator.

**Comment by andreasohlund** [comment] 2015-11-10 19:43
Looking at the response from http://localhost:33333/api/customchecks?status=unresolved
  

```
[
{
id: "df0acd20-2ca4-4eb8-1632-e3a141509bc6",
custom_check_id: "RetryRateCheck",
category: "MyCategory",
status: "pass",
reported_at: "2015-11-10T19:38:21.7255372Z",
originating_endpoint: {
name: "RetriesCustomCheckSample",
host_id: "fd9c16f5-8b4e-af7d-cfcb-6887a11366d4",
host: "ANDREAS2015"
}
}
]

```
It seems like there might be an issue with the filtering since as you can see the status is `pass`

**Comment by andreasohlund** [comment] 2015-11-10 19:45
Looking at https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/CustomChecks/CustomChecksModule.cs#L69 is seems like SC is expecting `fail` to be passed instead of `unresolved`

@petersgiles @colin-higgins ideas?

**Comment by andreasohlund** [comment] 2015-11-10 19:53
@petersgiles this commit seems to be the culprit https://github.com/Particular/ServicePulse/commit/b709cf940c6ab72aaed9b4b88cebbb3138dfb519#diff-2e8e4aea7512a76953509cb663ed9ce2

@mauroservienti please review and see if this is the issue with endpoints as well

**Comment by petersgiles** [comment] 2015-11-11 05:04
I have a fix for this now

**Closed** 2015-11-11 05:10 UTC
Labels: Type: Bug
