### ISSUE TITLE
Notifications should not result layout changes

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#284] opened 2016-02-15 10:36 UTC
If a notification pops up it results in the content of the page to temporarily rearrange. The grid moves down under the mouse pointer where a user can incorrectly select the wrong button.

Notifications should be behaving as overlays or have a reserved space on the page.

Overlays work better because they don't use screen estate.

Make sure that if multiple notifications occur on a smaller screen that these notifications do not conflict with the rest of the page and the user is still able to use the UI.

**Comment by sergioc** [comment] 2016-02-15 11:17
Duplicate of https://github.com/Particular/ServicePulse/issues/251

**Comment by ramonsmits** [comment] 2016-02-15 11:17
As a quick hack to stop the behavior I added these:

```css
    height: 100px;
    width: 80%;
    overflow: hidden;
    display: block;
    position: absolute;
```

**Closed by sergioc** 2016-02-15 11:17 UTC
Labels: Type: Bug

**Comment by petersgiles** [comment] 2016-02-15 22:37
@ramonsmits where did you do that hack?
We are currently doing a bunch of stuff around this https://github.com/Particular/ServicePulse/issues/251 

You are welcome to test and release this 
https://github.com/Particular/ServicePulse/pull/285

**Comment by WilliamBZA** [comment] 2016-02-16 06:43
@petersgiles It was directly in the browser using dev tools. Would have to be reapplied each time the browser opens.

**Comment by petersgiles** [comment] 2016-02-16 06:45
@WilliamBZA I assumed as much check this pull request https://github.com/Particular/ServicePulse/pull/285 where I have done what I think you guys did...feel free to release it as hotfix-1.3.9 is it does what you want it to do.
