### ISSUE TITLE
Access control for ServicePulse

### ISSUE THREAD

**Issue by nikolaimaric** [Particular/ServicePulse#1893] opened 2024-06-25 06:59 UTC
### Describe the feature.

It would be useful to have more proper user handling for the ServicePulse client - as it is today, access has to be restricted via firewall etc, and there is no notion of who can do what. 

A good place to start would be:
1. Add support for Entra ID logon.
2. Add basic support for user permissions (admin, read, delete, retry, edit & retry as separate permissions)
3. Add basic auditing - at the very least, show which user that deleted a message.

**Comment by danielmarbach** [comment] 2024-06-25 07:36
Thanks for the feedback. We are closing this one as a duplicate of:

- https://github.com/Particular/ServicePulse/issues/1723

**Closed by danielmarbach** 2024-06-25 07:36 UTC
