### ISSUE TITLE
Hamburger menus style is broken

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServicePulse#618] opened 2018-04-19 04:40 UTC
The hamburger menu is broken and does not render correctly.

![image](https://user-images.githubusercontent.com/132117/38971435-86045d52-43de-11e8-91c0-478629ce6bf2.png)

Running off the master - so latest build - in Chrome browser version 65.

**Comment by sergioc** [comment] 2018-04-19 06:10
Duplicate of #605

**Closed by sergioc** 2018-04-19 06:10 UTC
