### ISSUE TITLE
Should be possible to remove server from endpoint heartbeat list

### ISSUE THREAD

**Issue by nikolaimaric** [Particular/ServicePulse#756] opened 2019-06-24 08:49 UTC
When decomissioning a server/endpoint, there is no way to permanently remove it from the list of inactive endpoints in the "Endpoint heartbeats" section. The only option is to hide the endpoint, that is then restored as inactive every time ServicePulse is upgraded to a newer version.

![image](https://user-images.githubusercontent.com/1325611/66549161-fe665900-eb42-11e9-9d38-9de813519bcd.png)

One option could be to add a `Permanently remove` button near the `on/off` toggle:

![image](https://user-images.githubusercontent.com/1325611/66549396-7c2a6480-eb43-11e9-907c-eace1dd8868b.png)

Depends on https://github.com/Particular/ServiceControl/issues/1561

---

_Original description_

When we decomission a server, there is no way to permanently remove it from the endpoint monitoring. It can be disabled, but it is enabled again every time we upgrade ServicePulse. (Spoke with @janovesk about this at NDC Oslo last week, he suggested I file an issue)

**Comment by mauroservienti** [comment] 2019-06-24 12:36
Hi @nikolaimaric,

thanks for raising this and sorry for the issue. This issue is now monitored by the relevant group, it'd be probably prioritized for the next ServicePulse maintenance release. For which unfortunately I don't have an ETA.

Please subscribe to the issue updates, we'll post here further details.

**Comment by oskar** [comment] 2019-10-03 13:30
Any news on this? We are unable to rely on ServicePulse heartbeats for production system monitoring until there is a way to remove decommissioned endpoints.

**Comment by mauroservienti** [comment] 2019-10-10 07:22
I'm looking into this now, and I'm trying to scope the issue to better understand what needs to be done.

@nikolaimaric in your comment you refer to Monitoring, are you talking about the Monitoring section of ServicePulse?

![image](https://user-images.githubusercontent.com/1325611/66547196-fd332d00-eb3e-11e9-98d8-d8491997bed7.png)

@oskar, in your case, I guess you're referring to the fact that in the Heartbeats section once an Endpoint has failed reporting Heartbeat it's marked as inactive and there isn't really a way to **permanently** remove it:

![image](https://user-images.githubusercontent.com/1325611/66547339-4e432100-eb3f-11e9-89c1-51a6bc123e26.png)


Correct?

**Comment by oskar** [comment] 2019-10-10 07:43
We have the exact same issue as @nikolaimaric.

**Comment by nikolaimaric** [comment] 2019-10-10 07:50
![image](https://user-images.githubusercontent.com/8863648/66549293-45ece500-eb43-11e9-9e86-bc1f8415ce72.png)
Long story short: if you could add a Delete button next to the on/off toggle, we would be happy.

**Comment by mauroservienti** [comment] 2019-10-10 07:56
@nikolaimaric @oskar thanks for getting back to me so quickly. I've updated the issue description to better define the problem, please have a look.

The issue is still scheduled for the next ServicePulse maintenance release. For which unfortunately I don't have an ETA. I'll further investigate the impact/effort of this issue later today.

**Comment by mauroservienti** [comment] 2019-10-11 12:59
We're in the process of addressing this in https://github.com/Particular/ServicePulse/pull/791. This feature depends on a new API in ServiceControl, the new API will be released in https://github.com/Particular/ServiceControl/issues/1561 that is in progress as well. I don't think there will be a coordinate release as the ServicePulse feature is designed to detect the ServiceControl capability and react accordingly. Stay tuned for the coming announcements, and thanks for your patience.

**Comment by WilliamBZA** [comment] 2019-10-12 14:17
Will be release in version `1.23.0`. It needs a ServiceControl release too, so no need to release it now. I'll ping on this issue once ServiceControl is released too.

**Closed** 2019-10-12 14:16 UTC
Labels: candidate-for-next-release
