### ISSUE TITLE
Failed messages isn't making use of available space

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#524] opened 2017-10-09 11:35 UTC
The following screenshot shows that only 25% of the available width is used to render a single entry.

![image](https://user-images.githubusercontent.com/152998/31336130-c7f85450-acf5-11e7-9a2d-b9017778045e.png)

Alternatively, it could be much more like a normal table row with columns and make more use of the available space.

**Comment by WilliamBZA** [comment] 2017-10-09 13:10
@ramonsmits What else should be rendered there? Or are you suggesting that the text expands to fill the available space?

**Comment by ramonsmits** [comment] 2017-10-16 22:14
@WilliamBZA Yes, instead of using 3 rows for a single item to just have all on a single row, more like a grid row.

**Comment by WilliamBZA** [comment] 2017-10-17 06:03
That would impact users on smaller displays or systems with really long classifiers. I also tend to like the separation of concerns. @sergioc thoughts?

**Comment by ramonsmits** [comment] 2017-10-17 06:28
@WilliamBZA This is probably more a thing for responsive UI design. It is not specific to this row.

**Comment by sergioc** [comment] 2017-10-17 07:54
Yep, we could make this responsive.

**Comment by sergioc** [comment] 2018-04-18 17:43
Closing because:

1) @ramonsmits display resolution isn't that common
2) there's a whole row dedicated to group names because these can be very big
3) a row dedicated to each group of data/actions creates better visual hierarchy
4) this was designed with the assumption that there's never a large amount of groups, so screen real estate optimization is not critical

**Closed by sergioc** 2018-04-18 17:43 UTC
