### ISSUE TITLE
The group retry button seems a refresh button

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#264] opened 2016-02-11 05:36 UTC
It happens that users think that what we expose as a retry option for a given group is instead a way to refresh the group content, given that the icon is a refresh icon.

**Comment by sergioc** [comment] 2016-02-11 06:23
@petersgiles this is by design, so I'd say this update is more like a new feature.

**Comment by petersgiles** [comment] 2016-02-22 06:03
closing in favour of other issues that describe the problem better

**Closed by petersgiles** 2016-02-22 06:03 UTC
Labels: Type: Discussion
