### ISSUE TITLE
non-servicebus message body not shown in servicepulse

### ISSUE THREAD

**Issue by Inetfox** [Particular/ServicePulse#893] opened 2020-05-12 12:27 UTC
message body is not visible in servicepulse if (xml) message comes from a non nservicebus endpoint.

this issue got reported last year and was solved (https://github.com/Particular/ServicePulse/issues/723), but now we have the same issue again.

***************

Technical information

- ServicePulse version: 1.24.1
- ServiceControl version: 4.5.3
- Browser version: Firefox Quantum 68.7.0esr

**Comment by SzymonPobiega** [comment] 2020-05-14 10:39
Hi @Inetfox 

I used [SQL Server transport native integration sample](https://docs.particular.net/samples/sqltransport/native-integration/) to generate messages without headers and ServicePulse 1.25.1 was able to display the body. I tried JSON and XML in Chrome and Firefox

![image](https://user-images.githubusercontent.com/163318/81924828-e88cab00-95df-11ea-8a54-6c27e9c9a7ff.png)
![image](https://user-images.githubusercontent.com/163318/81924837-ecb8c880-95df-11ea-8e97-b966d57b85d8.png)

**Comment by Inetfox** [comment] 2020-05-14 13:11
Hi @SzymonPobiega 

thanks for looking into it.
I tested it also with Edge, but doesn't work either.

We have MSMQ as transport. Maybe it's a problem with the message-id?

over the api we can see that the message has the following message_id:
7d59ce25-6781-4eee-8b2d-3582378cf1bd\\383292856

Maybe this causes a wrong request, as get get a 404

![image](https://user-images.githubusercontent.com/7785435/81938430-2fd16680-95f5-11ea-9ff5-0e1c671de865.png)

**Comment by SzymonPobiega** [comment] 2020-05-15 08:52
@Inetfox Yes, that's probably the cause. This looks like a bug. I'll triage it and add it to our bug queue.

**Comment by WilliamBZA** [comment] 2020-08-08 07:48
Heads up: This will be fixed in the next version of ServiceControl. It is already fixed in master.

**Comment by WilliamBZA** [comment] 2020-08-17 10:34
4.12.0 of ServiceControl has been released!

**Closed by WilliamBZA** 2020-08-17 10:34 UTC
Labels: Type: Bug
