### ISSUE TITLE
May a failed message group content change during the retry process?

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServicePulse#267] opened 2016-02-11 06:06 UTC
What happens in an environment where the rate of failed messages is high?

If a user clicks on the `retry group` button and in the meantime new failed messages that logically belong to the same group are handled by ServiceControl are they going to be retried as well in the same retry attempt?

**Comment by johnsimons** [comment] 2016-02-11 06:10
Yes @mauroservienti, and this is by design

**Comment by mauroservienti** [comment] 2016-02-15 11:12
Why not add a cut off timestamp in the group query result sent to ServicePulse? When retrying only messages included in the group and that obey to the cut off rule will retried

**Comment by WilliamBZA** [comment] 2017-05-05 08:49
Raising this discussion from the dead because it came up while I was searching for other things 😄 

@mauroservienti There is a specific period where new messages could get added to the retry group: this can only happen before messages are marked for retry.

Now, we _could_ change the process to prevent this, but I'm not sure of the benefit and I might actually argue the opposite. Bear with me:

If a user is retrying a group, the assumption is they've fixed whatever bug was causing that error, or the network outage is resolved, or whatever. Retrying an entire group implies you want **all messages** that fit the classification of that group to be retried.

What if a message comes in while that group is being retried (but after marking has completed)? We have 2 scenarios here:

1. The incoming message is coming back into the group because the problem hasn't actually been fixed and all the other messages will come back in too. In this scenario, we should not re-retry these messages.

2. The incoming message was just not processed yet for whatever reason, and if it had been ingested earlier it would have formed part of the group that would have been retried. In this scenario, I think the message should still be retried as it matches the original classification of the group that the user wanted to retry.


From a user experience perspective things could get a little confusing though unless the user is very clear on the process.  Examples:

Example 1: User retries a group and scenario 2 occurs: 
_I retried this group, why are there 5 messages in the group even after SP has told me the group has been retried? Are these new messages? Is my system still broken?_

Example 2: User retries a group and scenario 1 occurs:
_I retried this group, why are there 5 messages in the group even after SP has told me the group has been retried? Are these new messages? Is my system still broken?_

Users might ask the same questions in both examples, and we should ideally be able to communicate to the user why the group is still there. Arguably, example 1 should not happen, which would mean we only have example 2 left - making it a lot easier to convey to the user the **why** of why there are still messages in the group.

**Comment by WojcikMike** [comment] 2017-05-05 10:10
Yeah, I remember being part of the discussion about it a few times already. And every time we came down to the fact that we assume that in scenario 2 we want to retry those messages. While in scenario 1 we acknowledge the redundancy of such action. 

One could make a claim that if we retry a group and first batch fail we should stop retrying as there is not point in doing that.

**Comment by WojcikMike** [comment] 2018-04-12 09:59
We had that discussion number of times, on different occasions. At the moment group is a temporal aggregate for a set of messages. It is not an entity and when you click retry you basically retry all messages that at that time were in group. Changing that would require a bigger change in ServiceControl. I am closing this issue. Maybe in the future we will revise our approach.

**Closed by WojcikMike** 2018-04-12 09:59 UTC
Labels: Type: Discussion
