### ISSUE TITLE
Web socket error

### ISSUE THREAD

**Issue by neutrongenious** [Particular/ServicePulse#411] opened 2017-02-22 20:43 UTC
WebSocket connection to 'ws://servername/servicecontrol/api/messagestream/connect?transport=webSockets&clientProtocol=1.5&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAWx%2BSr7lYK0arHZ%2FfRgQ29wAAAAACAAAAAAAQZgAAAAEAACAAAAAL0sH6%2FYUgI0xC9bfuXvxWBTrwnlsABtOIWEfX8FzKKQAAAAAOgAAAAAIAACAAAAAKxh0EBZEgs8kuUuxfdDqym3UFCLL%2B3ZhOgQFexeQCrzAAAADmrwKJW549zlHH%2FGzjrcMJgMsCxvNuokK09MQHhffRe9pajVNkA9%2BxyFqivfLceM1AAAAABtNlDs5o2cStWT0qSkgczzJWqDlXYVLmqV9fB2uR3M6hspmicH5%2BctfRkga23XBqrJ3FKiTfXg0z05jsK9mdIQ%3D%3D&tid=0' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

**Comment by indualagarsamy** [comment] 2017-02-22 20:59
Hi @neutrongenious - What versions of ServicePulse and ServiceControl are you currently using? And where are you seeing this error? Can you describe the steps to reproduce this? Thank you.

**Comment by indualagarsamy** [comment] 2017-02-28 01:32
Hi @neutrongenious - What browser are you using? It could possibly be a browser issue with SignalR. See: https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms

**Comment by neutrongenious** [comment] 2017-03-06 20:21
Hi Guys,
I am using chrome.
I am running latest version of ServicePulse and ServiceControl.

Servicecontrol api is running behind iis reverse proxy.

**Comment by indualagarsamy** [comment] 2017-03-07 19:27
@Particular/servicepulse-maintainers - any ideas?

**Comment by indualagarsamy** [comment] 2017-03-07 19:33
@neutrongenious - You mentioned that ServiceControl API is running behind IIS reverse proxy. There is a known bug in SignalR. Make sure that the reverse proxy is setup correctly. See the following documentation:

https://docs.particular.net/servicepulse/install-servicepulse-in-iis#advanced-configuration

**Comment by WilliamBZA** [comment] 2017-03-08 07:10
@neutrongenious As @indualagarsamy pointed out, the configuration of the reverse proxy is very specific. Are you able to share the configuration you are using?
Are you running the reverse proxy in the root dir?

For reference, [here](https://github.com/SignalR/SignalR/issues/3649) is an issue open in the SignalR repo to address this. I have little hope that they will fix this before the next SignalR major release.

**Comment by sergioc** [comment] 2018-04-18 14:42
Closing issue due to lack of more data to use for further investigation.

@neutrongenious feel free to re-open this issue if you're able to answer @WilliamBZA's questions.

**Closed by sergioc** 2018-04-18 14:42 UTC
