### ISSUE TITLE
Allow free form user comments for retry groups

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#393] opened 2017-01-17 17:10 UTC
See the user feedback here: https://groups.google.com/forum/#!topic/particularsoftware/TdkL7i36ioA

>It would be great if there could be a free form field at the message group level where we could leave comments about what actions had been taken.

**Comment by janovesk** [comment] 2017-01-20 20:12
Interesting.. What should we connect it to? The current open group? What if you request a retry for the group and new, similar messages make the group reappear later? Should the "old" comment pop back up, or was that "cleared" by the retry operation?

**Comment by stimms** [comment] 2017-01-20 22:11
Great questions. I would say that the message should be cleared by a `retry all` but not with a retry of a single message. In our scenario we see errors which are caused by upstream processes which are failing. Until they are corrected we just need to keep the ops team, who work 24/7, aware that there is no point in retrying. We use to use labels in MSMQ for this purpose. I'd tie the message to the current group and I wouldn't revive the message if the group is cleared and then new messages come in.

**Comment by WilliamBZA** [comment] 2017-01-21 09:10
Connected to this suggestion: https://github.com/Particular/ServicePulse/issues/164

Perhaps an approach that allows comments on groups, operations, endpoints, custom checks, etc might be a good initiative.

**Comment by sergioc** [comment] 2017-01-23 17:33
Could we somehow have a generic ability to add comments to any SC event and then expose where appropriate in SP?

**Comment by efleming18** [comment] 2017-07-12 15:18
@WilliamBZA Any movement on this one?

**Comment by WilliamBZA** [comment] 2017-07-14 09:58
@efleming18 I'm trying to come up with a way to add this feature without adding too much additional load on RavenDb. It's a bit tricky because of how we like the groups to the actual failed messages.

On the assumption that I manage to come up with something clever for the storage, there's a few decisions that should be made first:

* If a group has  for e.g. a tag of `Prod bug`, when that group is archived or retried, and the group is effectively closed, are the tags closed too? This is related to @janovesk's question above.
* How "free" are we talking when we talk about free text? I'm leaning towards simple tags for now, but even those should have a limit (maybe limit 3 tags per group? Perhaps even limit it to 1 tag for now?)
* I think it's clear that these tags belong at a group level and not a message level, meaning that if the grouping is changed, should the tags follow?

@stimms already gave a pretty good example of how this would be used, perhaps we can come up with a few other scenarios so that we can trim down the requirements a bit more.

**Comment by WojcikMike** [comment] 2018-04-12 11:16
There is an ask for similar feature in #164

**Comment by WojcikMike** [comment] 2021-06-23 09:20
We added the ability to comment on a group in version 1.30 of ServicePulse. Close this issues

**Closed by WojcikMike** 2021-06-23 09:20 UTC
Labels: Type: Feature, User feedback
